### PR TITLE
bump to latest dependency versions

### PR DESCRIPTION
**Pull request by snodnipper**

### CODE REVIEW

**Comment by snodnipper** [comment]
I am also pushing for 1.6 compatibility so that we can bump the JSON dependency.

https://github.com/douglascrockford/JSON-java/issues/156#issuecomment-147193957

**Comment by climbage** [comment]
@stolstov Anything reason not to merge this?

**Comment by randallwhitman** [comment]
The dependency version changes look OK to me.
Tangentially, is there still reason for Esri to have a [JSON fork](https://github.com/Esri/JSON-java)?  Is upstream interested in the [Ant build support](https://github.com/stleary/JSON-java/compare/master...Esri:master)?

**Comment by stolstov** [comment]
@randallwhitman The JSON fork question is too tangential to be discussed there :)

**Pull request merged**
