### PR TITLE
cleaning up decimal places for automated conversion to C#

### PR DESCRIPTION
**Pull request by davidraleigh**
Floats that have a decimal place and no tenths position make xamarin studio unhappy.

### CODE REVIEW

**Comment by randallwhitman** [comment]
Is the bug in geometry-api-java or/versus in xamarin studio?

**Comment by stolstov** [comment]
@randallwhitman Neither Eclipse nor Netbeans complain. But the definite answer is in the Java standard.

**Comment by stolstov** [comment]
http://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.10.2
Seems to be "0.5", ".5", and "5.0" and "5." are all valid in Java. They are also valid in C++.

**Comment by stolstov** [comment]
@davidraleigh Could you submit a pull request that only contain changes related to the decimal point use?

**Comment by davidraleigh** [comment]
Yeah, I'm not sure while all the other changes got pushed into this pull request. I'll do it over.

**Pull request closed without merging**
