### PR TITLE
centroid fixes

### PR DESCRIPTION
**Pull request by stolstov**
Issue: https://github.com/Esri/geometry-api-java/issues/225

Fix polyline centroid (original would only take endpoints of polyline paths)
Zero area polygon delegates to the polyline centroid and zero length polyline delegates to the multipoint centroid.
Rewrite polygon centroid for better accuracy.

@jagill I've copied your test cases
@mbasmanova 
@alocke

### CODE REVIEW

**Comment by stolstov** [comment]
I've fixed travis build for openjdk. Have problem with oracle.
For the oraclejdk9 
Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8 or one of its dependencies could not be resolved

**Comment by stolstov** [comment]
I've added openjdk14 for which I've updated the source and target of java to 1.7
Travis has some new error with oraclejdk. I don't know how to fix this:
 Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.8

**Comment by stolstov** [comment]
I've commented out oracle jdk from travis.yml. Now the checks pass. Please, let me know if there is other way to fix the Travis CI build.

**Comment by randallwhitman** [comment]
@stolstov By any chance does the Travis build work with Oracle-JDK-11?  I wouldn't worry about 9 or 10 which are obsoleted by 11.

**Comment by stolstov** [comment]
@randallwhitman Thanks, oraclejdk11 works indeed. I'll leave it at that.

**Comment by randallwhitman** [comment]
Sounds good.  Only remaining suggestion about that would be to likewise upgrade OpenJDK to 11 and forget 9-10.

**Comment by stolstov** [comment]
It builds openjdk 9,10, and 14 right now.

**Comment by alocke** [comment]
@stolstov I added a few test cases to your branch. It looks good to me.

**Comment by stolstov** [comment]
@alocke Thank you. I'll install this tomorrow if I don't hear negative feedback.

**Pull request merged**
