### PR TITLE
Fix a hang in union of a point with polyline

### PR DESCRIPTION
**Pull request by stolstov**
Fix the issue https://github.com/Esri/geometry-api-java/issues/266

### CODE REVIEW

**Comment by stolstov** [comment]
@jagill This should fix the hang in geometry.

**Comment by jagill** [comment]
Thanks for the quick fix!  When do you think the next point release might be?

**Comment by zhanshi-wang** [comment]
@randallwhitman  Is it possible to have the next release sooner? We are blocked by this issue.

**Comment by randallwhitman** [comment]
In the meantime you can build from master and `mvn install`.

**Comment by randallwhitman** [comment]
https://github.com/Esri/geometry-api-java/releases/tag/v2.2.4

**Pull request merged**
