### PR TITLE
A fix for geodist hang

### PR DESCRIPTION
**Pull request by stolstov**
A fix for issue #75 provided by @daburrows. Adds a check for max iteration count.
#100 
@manasdebashiskar
@movermeyer
@alocke

### CODE REVIEW

**Comment by alocke** [comment]
Tested the fix. It looks good.

**Comment by stolstov** [comment]
@alocke Great! I'll wait a couple of days before merge to give an interested persons time to test the fix on their data.

**Comment by movermeyer** [comment]
+1 Works with my data.

**Comment by stolstov** [comment]
@movermeyer Thanks!

**Pull request merged**
