### PR TITLE
Dev1.2.1

### PR DESCRIPTION
**Pull request by stolstov**
@alocke 
@abalog 
@climbage 
@randallwhitman 
Fixes issues #74 #71 #63 #62 #61

### CODE REVIEW

**Comment by climbage** [comment]
@stolstov This looks good to me.

**Comment by randallwhitman** [comment]
Go ahead - my tests pass.
If you want, one detail in a comment in NonSimpleResult: s/interioir/interior/ .

**Comment by stolstov** [comment]
@randallwhitman What detail?

**Comment by randallwhitman** [comment]
An extra 'i' in misspelled "interior" in the comment for OGCPolygonSelfTangency, line 80.

**Comment by stolstov** [comment]
@randallwhitman I see... We'll fix this next time.

**Comment by randallwhitman** [comment]
Confirm that the ST_Geometry/Hive test scripts run OK after the recent commit.

**Comment by alocke** [comment]
All tests pass.

**Comment by stolstov** [comment]
@climbage Lets merge?

**Comment by climbage** [comment]
@stolstov sounds good.  I can push to maven after.

**Comment by stolstov** [comment]
@alocke I've assigned bunch of issues to verify to you if you do not mind:)

**Comment by climbage** [comment]
Sure.  I'm in no hurry.

**Comment by alocke** [comment]
@climbage I have verified all the fixes that were merged into master.

**Comment by climbage** [comment]
Sounds good.  I'll push to maven.

**Comment by stolstov** [comment]
@climbage Here is url for fixed issues to add to the release description: https://github.com/Esri/geometry-api-java/issues?q=is%3Aissue+is%3Aclosed+milestone%3A1.2.1

**Pull request merged**
