### PR TITLE
removed org.json dependency

### PR DESCRIPTION
**Pull request by stolstov**
Breaking API change for #131 and for #135. So need a version bump.

Also, upgraded to fasterxml.jackson from the codehaus one.
Removed dependency on the JSONObject from org.json.

I've added a sample how to wrap JSONObject to the samples repo: https://github.com/Esri/samples-geometry-api-java.

https://github.com/Esri/samples-geometry-api-java/blob/sergey/json_object_reader/JsonObjectReader/src/test/java/com/esri/core/geometry/examples/JsonObjectReaderTest.java

@alocke

### CODE REVIEW

**Comment by randallwhitman** [comment]
Skimmed - overall it looks like it should be good.

**Comment by randallwhitman** [comment]
@stolstov Did this or did this not cover everything we wanted to change, with JSON-related exceptions, when we have the opportunity at v2 - #109/#115/#126 - ?
cc @kjkrum

**Comment by stolstov** [comment]
@randallwhitman Yes.

**Comment by randallwhitman** [comment]
Excellent - thanks for confirming @stolstov

**Pull request merged**
