### PR TITLE
fix a bug in generalize for large deviations

### PR DESCRIPTION
**Pull request by stolstov**
A fix for issue #98 
@FalconIA

### CODE REVIEW

**Comment by alocke** [comment]
With this fix if maxDeviation = 1.6 and bRemoveDegenerateParts = false, an empty polygon is returned. If maxDeviation = 1.5 and bRemoveDegenerateParts = false, the correct degenerate polygon is returned.

**Comment by stolstov** [comment]
@alocke Could you check this install, if it fixes the issue you found?

**Comment by alocke** [comment]
No, it doesn't work. If maxDeviation = 1.6 and bRemoveDegenerateParts = false, an empty polygon is returned.

**Comment by stolstov** [comment]
@alocke Strange. I've added a unit test that demonstrates that this should work. Although, it does not use the original data.

**Comment by alocke** [comment]
Oops, my build was messed up. Looks good.

**Pull request merged**
