### PR TITLE
Add serialization for QuadTree and related classes

### PR DESCRIPTION
**Pull request by stolstov**
Issue: https://github.com/Esri/geometry-api-java/issues/186

@julieromm

### CODE REVIEW

**Comment by stolstov** [comment]
Replaces https://github.com/Esri/geometry-api-java/pull/185

**Comment by randallwhitman** [comment]
@stolstov I'll defer to you rather than attempt an adequate review.

**Comment by julieromm** [comment]
@stolstov just wondering when this can be expected to be merged.  Thanks!

**Comment by stolstov** [comment]
@julieromm Sorry for the delay, I was on vacation.

**Pull request merged**
