### PR TITLE
don't use JSONObject.getNames for Android

### PR DESCRIPTION
**Pull request by stolstov**
@kjkrum Please, review this fix instead of your pull request #124.

### CODE REVIEW

**Comment by kjkrum** [comment]
Your approach is probably better.  I just wanted to touch as few existing lines as possible.

**Comment by stolstov** [comment]
@randallwhitman @climbage Could you review too?

**Comment by randallwhitman** [comment]
I've taken a look at the diff, and I'll defer to you, Sergey.

**Comment by stolstov** [comment]
Removed unneeded checks, added a check for object length before getting the iterator (to match JSONObject.getNames)

**Pull request merged**
