### PR TITLE
Fix for SpatialReferenceImpl.equals(Object) - compare different values

### PR DESCRIPTION
**Pull request by panchenko**

### CODE REVIEW

**Comment by stolstov** [comment]
@panchenko Thanks! The fix looks good. Could you change the unit test like that (TestSpatialReference.java):
```
package com.esri.core.geometry;

import junit.framework.TestCase;
import org.junit.Test;

public class TestSpatialReference extends TestCase {
	@Test
	public void testEquals() {
		final SpatialReference a = SpatialReference.create("GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]");
		final SpatialReference b = SpatialReference.create("PROJCS[\"WGS_1984_Web_Mercator_Auxiliary_Sphere\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Mercator_Auxiliary_Sphere\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],PARAMETER[\"Auxiliary_Sphere_Type\",0.0],UNIT[\"Meter\",1.0]]");
		final SpatialReference c = SpatialReference.create("GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]");
		assertTrue(a.equals(a));
		assertTrue(b.equals(b));
		assertTrue(a.equals(c));
		assertTrue(!a.equals(b));
		assertTrue(!b.equals(a));
	}
}
```

**Comment by panchenko** [comment]
@stolstov Why a combination of juni3/junit4 styles? it looks confusing.

**Comment by stolstov** [comment]
@panchenko I only can say that it works like that too :). The naming convention should stay but feel free to fix this to a better style.

**Comment by panchenko** [comment]
@stolstov I've updated this test

**Pull request merged**
